# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.8.4

    working_directory: ~/repo

    steps:
      - checkout:
      - run:
          name: pull changes from merge
          command: |
            if [[ -v CI_PULL_REQUEST ]] ; then git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge" ; fi

      - run:
          name: create virtual environment, install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y graphviz texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-generic-extra latexmk texlive-xetex
            python3.8 -m venv venv
            . venv/bin/activate

      - run:
          name: build numpy
          command: |
            . venv/bin/activate
            pip install --progress-bar=off --upgrade pip 'setuptools<49.2.0'
            pip install --progress-bar=off -r test_requirements.txt
            pip install .
            pip install --progress-bar=off -r doc_requirements.txt

      - run:
          name: create release notes
          command: |
            . venv/bin/activate
            pip install git+https://github.com/hawkowl/towncrier.git@master
            VERSION=$(python -c "import setup; print(setup.VERSION)")
            towncrier --version $VERSION --yes
            ./tools/ci/test_all_newsfragments_used.py

      - run:
          name: run doctests on documentation
          command: |
            . venv/bin/activate
            (cd doc ; git submodule update --init)
            python tools/refguide_check.py --rst

      - run:
          name: build devdocs w/ref warnings
          command: |
            . venv/bin/activate
            cd doc
            # Don't use -q, show warning summary"
            SPHINXOPTS="-n" make -e html || echo "ignoring errors for now, see gh-13114"

      - run:
          name: build devdocs
          command: |
            . venv/bin/activate
            cd doc
            make clean
            SPHINXOPTS=-q make -e html

      - run:
          name: build neps
          command: |
            . venv/bin/activate
            cd doc/neps
            SPHINXOPTS=-q make -e html
